name: libplctag_dart
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  ffi: ^2.1.0
  tuple: ^2.0.0
  bit_array: ^2.2.0

dev_dependencies:
  ffigen: ^11.0.0
  test: ^1.24.0

ffigen:
  output: 'lib/native/generated_bindings.dart'
  headers:
    entry-points:
      - 'libplctag.h'
    include-directives:
      - 'libplctag.h'
  functions:
    include:
      - 'plc_tag_.*'
  macros:
    include:
      - 'PLCTAG_.*'
      - 'PLC_TAG_.*'
  enums:
    include:
      - 'plctag_.*'
  structs:
    include:
      - 'plctag_.*'
  unnamed-enums:
    include:
      - 'PLCTAG_.*'
      - 'PLC_TAG_.*'