// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// @brief Convert error code to human-readable string.
  ///
  /// Takes one of the error codes and turns it into a const char * suitable
  /// for printing.
  ///
  /// @param err Error code to decode.
  /// @return Human-readable error string.
  ffi.Pointer<ffi.Char> plc_tag_decode_error(
    int err,
  ) {
    return _plc_tag_decode_error(
      err,
    );
  }

  late final _plc_tag_decode_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int)>>(
          'plc_tag_decode_error');
  late final _plc_tag_decode_error = _plc_tag_decode_errorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  void plc_tag_set_debug_level(
    int debug_level,
  ) {
    return _plc_tag_set_debug_level(
      debug_level,
    );
  }

  late final _plc_tag_set_debug_levelPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
          'plc_tag_set_debug_level');
  late final _plc_tag_set_debug_level =
      _plc_tag_set_debug_levelPtr.asFunction<void Function(int)>();

  /// @brief Set debug level for a specific module.
  ///
  /// Allows fine-grained control over debug output by setting the debug level
  /// for a specific module independently of the global debug level.
  ///
  /// @param module Module ID from the plctag_debug_module_t enum.
  /// @param debug_level Debug level value (same as plc_tag_set_debug_level()).
  /// @return PLCTAG_STATUS_OK on success, PLCTAG_ERR_BAD_PARAM if arguments are out of range.
  int plc_tag_set_debug_module_level(
    int module,
    int debug_level,
  ) {
    return _plc_tag_set_debug_module_level(
      module,
      debug_level,
    );
  }

  late final _plc_tag_set_debug_module_levelPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int32, ffi.Int)>>(
          'plc_tag_set_debug_module_level');
  late final _plc_tag_set_debug_module_level =
      _plc_tag_set_debug_module_levelPtr.asFunction<int Function(int, int)>();

  /// @brief Get the debug level for a specific module.
  ///
  /// @param module Module ID from the plctag_debug_module_t enum.
  /// @return Current debug level for the specified module.
  int plc_tag_get_debug_module_level(
    int module,
  ) {
    return _plc_tag_get_debug_module_level(
      module,
    );
  }

  late final _plc_tag_get_debug_module_levelPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int32)>>(
          'plc_tag_get_debug_module_level');
  late final _plc_tag_get_debug_module_level =
      _plc_tag_get_debug_module_levelPtr.asFunction<int Function(int)>();

  /// @brief Get the current global debug level.
  ///
  /// @return Current global debug level set by plc_tag_set_debug_level().
  int plc_tag_get_debug_level() {
    return _plc_tag_get_debug_level();
  }

  late final _plc_tag_get_debug_levelPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
          'plc_tag_get_debug_level');
  late final _plc_tag_get_debug_level =
      _plc_tag_get_debug_levelPtr.asFunction<int Function()>();

  /// @brief Check that the library supports the required API version.
  ///
  /// The version is passed as integers with the following semantics:
  /// - ver_major: major version of the library (must be an exact match).
  /// - ver_minor: minor version (library version must be >= requested).
  /// - ver_patch: patch version (must be >= requested if minor matches; any patch is accepted if library minor > requested).
  ///
  /// @param req_major Required major version number.
  /// @param req_minor Required minor version number.
  /// @param req_patch Required patch version number.
  /// @return PLCTAG_STATUS_OK if version is compatible, PLCTAG_ERR_UNSUPPORTED if not.
  ///
  /// @note Example: To check for version 2.1.4, call plc_tag_check_lib_version(2, 1, 4).
  int plc_tag_check_lib_version(
    int req_major,
    int req_minor,
    int req_patch,
  ) {
    return _plc_tag_check_lib_version(
      req_major,
      req_minor,
      req_patch,
    );
  }

  late final _plc_tag_check_lib_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int, ffi.Int)>>(
          'plc_tag_check_lib_version');
  late final _plc_tag_check_lib_version =
      _plc_tag_check_lib_versionPtr.asFunction<int Function(int, int, int)>();

  /// @brief Create a new tag based on an attribute string.
  ///
  /// Creates a new tag based on the passed attribute string. The attributes
  /// are protocol-specific. The only required part of the string is the key-value pair
  /// "protocol=XXX" where XXX is one of the supported protocol types.
  ///
  /// The function will wait for the specified timeout (in milliseconds) for the tag
  /// to finish the creation process. If timeout is zero, return immediately.
  /// The application will need to poll the tag status with plc_tag_status() while
  /// the status is PLCTAG_STATUS_PENDING until the status changes to PLCTAG_STATUS_OK
  /// (if successful) or another PLCTAG_ERR_xyz error code.
  ///
  /// @param attrib_str Protocol-specific attribute string (must include "protocol=XXX").
  /// @param timeout Milliseconds to wait for creation (0 = return immediately).
  /// @return Opaque tag handle (>0 on success, <0 on error with PLCTAG_ERR_xyz code).
  int plc_tag_create(
    ffi.Pointer<ffi.Char> attrib_str,
    int timeout,
  ) {
    return _plc_tag_create(
      attrib_str,
      timeout,
    );
  }

  late final _plc_tag_createPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Char>, ffi.Int)>>(
      'plc_tag_create');
  late final _plc_tag_create =
      _plc_tag_createPtr.asFunction<int Function(ffi.Pointer<ffi.Char>, int)>();

  /// @brief Create a new tag with callback support.
  ///
  /// Extended version of plc_tag_create() with the addition of a callback function
  /// and user-supplied data pointer.
  ///
  /// The callback will be set as early as possible in the creation process,
  /// allowing early creation-time events to be sent to user code.
  ///
  /// @param attrib_str Protocol-specific attribute string (must include "protocol=XXX").
  /// @param tag_callback_func Callback function for tag events.
  /// @param userdata User-supplied data pointer passed to callback.
  /// @param timeout Milliseconds to wait for creation (0 = return immediately).
  /// @return Opaque tag handle (>0 on success, <0 on error with PLCTAG_ERR_xyz code).
  int plc_tag_create_ex(
    ffi.Pointer<ffi.Char> attrib_str,
    ffi.Pointer<
            ffi.NativeFunction<
                ffi.Void Function(ffi.Int32 tag_id, ffi.Int event,
                    ffi.Int status, ffi.Pointer<ffi.Void> userdata)>>
        tag_callback_func,
    ffi.Pointer<ffi.Void> userdata,
    int timeout,
  ) {
    return _plc_tag_create_ex(
      attrib_str,
      tag_callback_func,
      userdata,
      timeout,
    );
  }

  late final _plc_tag_create_exPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<
                  ffi.NativeFunction<
                      ffi.Void Function(ffi.Int32 tag_id, ffi.Int event,
                          ffi.Int status, ffi.Pointer<ffi.Void> userdata)>>,
              ffi.Pointer<ffi.Void>,
              ffi.Int)>>('plc_tag_create_ex');
  late final _plc_tag_create_ex = _plc_tag_create_exPtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<
              ffi.NativeFunction<
                  ffi.Void Function(ffi.Int32 tag_id, ffi.Int event,
                      ffi.Int status, ffi.Pointer<ffi.Void> userdata)>>,
          ffi.Pointer<ffi.Void>,
          int)>();

  /// @brief Create a new tag based on an existing tag.
  ///
  /// @param src_tag_id Source tag ID to copy attributes from.
  /// @param attrib_str additional attributes for a tag based on the protocol and device of the source tag.
  /// @param tag_callback_func Callback function for tag events.
  /// @param userdata User-supplied data pointer passed to callback.
  /// @param timeout Milliseconds to wait for creation (0 = return immediately).
  /// @return Opaque tag handle (>0 on success, <0 on error with PLCTAG_ERR_xyz code).
  int plc_tag_create_from_tag(
    int src_tag_id,
    ffi.Pointer<ffi.Char> attrib_str,
    ffi.Pointer<
            ffi.NativeFunction<
                ffi.Void Function(ffi.Int32 tag_id, ffi.Int event,
                    ffi.Int status, ffi.Pointer<ffi.Void> userdata)>>
        tag_callback_func,
    ffi.Pointer<ffi.Void> userdata,
    int timeout,
  ) {
    return _plc_tag_create_from_tag(
      src_tag_id,
      attrib_str,
      tag_callback_func,
      userdata,
      timeout,
    );
  }

  late final _plc_tag_create_from_tagPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Int32,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<
                  ffi.NativeFunction<
                      ffi.Void Function(ffi.Int32 tag_id, ffi.Int event,
                          ffi.Int status, ffi.Pointer<ffi.Void> userdata)>>,
              ffi.Pointer<ffi.Void>,
              ffi.Int)>>('plc_tag_create_from_tag');
  late final _plc_tag_create_from_tag = _plc_tag_create_from_tagPtr.asFunction<
      int Function(
          int,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<
              ffi.NativeFunction<
                  ffi.Void Function(ffi.Int32 tag_id, ffi.Int event,
                      ffi.Int status, ffi.Pointer<ffi.Void> userdata)>>,
          ffi.Pointer<ffi.Void>,
          int)>();

  /// @brief Shut down the library and release all resources.
  ///
  /// Some systems may not call the atexit() handlers. In those cases, wrappers should
  /// call this function before unloading the library or terminating. Most OSes cleanly
  /// recover all system resources when a process terminates, so this may not be necessary.
  ///
  /// @warning THIS IS NOT THREAD SAFE! Do not call this if multiple threads are running
  /// against the library. Close all tags first with plc_tag_destroy() and ensure
  /// that nothing can call any library functions until this function returns.
  ///
  /// @note Normally you do not need to call this function. This is only for certain
  /// wrappers or operating environments that prevent normal exit handlers from working.
  void plc_tag_shutdown() {
    return _plc_tag_shutdown();
  }

  late final _plc_tag_shutdownPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('plc_tag_shutdown');
  late final _plc_tag_shutdown =
      _plc_tag_shutdownPtr.asFunction<void Function()>();

  /// @brief Register a callback function for tag events.
  ///
  /// Registers the passed callback function with the tag. Only one callback function
  /// may be registered on a tag at a time.
  ///
  /// Once registered, the callback will be invoked for these events:
  /// - PLCTAG_EVENT_READ_STARTED: When a tag read operation starts.
  /// - PLCTAG_EVENT_READ_COMPLETED: When a tag read operation completes.
  /// - PLCTAG_EVENT_WRITE_STARTED: When a tag write operation starts.
  /// - PLCTAG_EVENT_WRITE_COMPLETED: When a tag write operation completes.
  /// - PLCTAG_EVENT_ABORTED: When a tag operation is aborted.
  /// - PLCTAG_EVENT_DESTROYED: When a tag is being destroyed.
  /// - PLCTAG_EVENT_CREATED: When a tag is created.
  ///
  /// @warning The callback is called outside the internal tag mutex, allowing it to call
  /// tag functions safely. However, it is called in the context of the internal
  /// tag helper thread, not the client library thread(s). YOU are responsible for
  /// ensuring all client application data structures accessed by the callback are
  /// thread-safe.
  ///
  /// @warning Do not perform blocking operations in the callback. This will degrade
  /// library performance or cause failures.
  ///
  /// @warning When the callback is called with PLCTAG_EVENT_DESTROYED, do not call
  /// any tag functions as they are not guaranteed to work and may hang or fail.
  ///
  /// @param tag_id The tag ID handle returned by plc_tag_create().
  /// @param tag_callback_func Callback function pointer.
  /// @return PLCTAG_STATUS_OK on success, PLCTAG_ERR_DUPLICATE if a callback is already registered.
  int plc_tag_register_callback(
    int tag_id,
    ffi.Pointer<
            ffi.NativeFunction<
                ffi.Void Function(
                    ffi.Int32 tag_id, ffi.Int event, ffi.Int status)>>
        tag_callback_func,
  ) {
    return _plc_tag_register_callback(
      tag_id,
      tag_callback_func,
    );
  }

  late final _plc_tag_register_callbackPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Int32,
              ffi.Pointer<
                  ffi.NativeFunction<
                      ffi.Void Function(ffi.Int32 tag_id, ffi.Int event,
                          ffi.Int status)>>)>>('plc_tag_register_callback');
  late final _plc_tag_register_callback =
      _plc_tag_register_callbackPtr.asFunction<
          int Function(
              int,
              ffi.Pointer<
                  ffi.NativeFunction<
                      ffi.Void Function(ffi.Int32 tag_id, ffi.Int event,
                          ffi.Int status)>>)>();

  /// @brief Register a callback function for tag events with user data.
  ///
  /// Extended version of plc_tag_register_callback() that includes a user-supplied
  /// data pointer passed to the callback function.
  ///
  /// @param tag_id The tag ID handle returned by plc_tag_create().
  /// @param tag_callback_func Callback function pointer.
  /// @param userdata User-supplied data pointer passed to callback.
  /// @return PLCTAG_STATUS_OK on success, PLCTAG_ERR_DUPLICATE if a callback is already registered.
  ///
  /// @see plc_tag_register_callback()
  int plc_tag_register_callback_ex(
    int tag_id,
    ffi.Pointer<
            ffi.NativeFunction<
                ffi.Void Function(ffi.Int32 tag_id, ffi.Int event,
                    ffi.Int status, ffi.Pointer<ffi.Void> userdata)>>
        tag_callback_func,
    ffi.Pointer<ffi.Void> userdata,
  ) {
    return _plc_tag_register_callback_ex(
      tag_id,
      tag_callback_func,
      userdata,
    );
  }

  late final _plc_tag_register_callback_exPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Int32,
              ffi.Pointer<
                  ffi.NativeFunction<
                      ffi.Void Function(ffi.Int32 tag_id, ffi.Int event,
                          ffi.Int status, ffi.Pointer<ffi.Void> userdata)>>,
              ffi.Pointer<ffi.Void>)>>('plc_tag_register_callback_ex');
  late final _plc_tag_register_callback_ex =
      _plc_tag_register_callback_exPtr.asFunction<
          int Function(
              int,
              ffi.Pointer<
                  ffi.NativeFunction<
                      ffi.Void Function(ffi.Int32 tag_id, ffi.Int event,
                          ffi.Int status, ffi.Pointer<ffi.Void> userdata)>>,
              ffi.Pointer<ffi.Void>)>();

  int plc_tag_unregister_callback(
    int tag_id,
  ) {
    return _plc_tag_unregister_callback(
      tag_id,
    );
  }

  late final _plc_tag_unregister_callbackPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int32)>>(
          'plc_tag_unregister_callback');
  late final _plc_tag_unregister_callback =
      _plc_tag_unregister_callbackPtr.asFunction<int Function(int)>();

  int plc_tag_register_logger(
    ffi.Pointer<
            ffi.NativeFunction<
                ffi.Void Function(ffi.Int32 tag_id, ffi.Int debug_level,
                    ffi.Pointer<ffi.Char> message)>>
        log_callback_func,
  ) {
    return _plc_tag_register_logger(
      log_callback_func,
    );
  }

  late final _plc_tag_register_loggerPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  ffi.Pointer<
                      ffi.NativeFunction<
                          ffi.Void Function(
                              ffi.Int32 tag_id,
                              ffi.Int debug_level,
                              ffi.Pointer<ffi.Char> message)>>)>>(
      'plc_tag_register_logger');
  late final _plc_tag_register_logger = _plc_tag_register_loggerPtr.asFunction<
      int Function(
          ffi.Pointer<
              ffi.NativeFunction<
                  ffi.Void Function(ffi.Int32 tag_id, ffi.Int debug_level,
                      ffi.Pointer<ffi.Char> message)>>)>();

  int plc_tag_unregister_logger() {
    return _plc_tag_unregister_logger();
  }

  late final _plc_tag_unregister_loggerPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
          'plc_tag_unregister_logger');
  late final _plc_tag_unregister_logger =
      _plc_tag_unregister_loggerPtr.asFunction<int Function()>();

  int plc_tag_lock(
    int tag,
  ) {
    return _plc_tag_lock(
      tag,
    );
  }

  late final _plc_tag_lockPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int32)>>('plc_tag_lock');
  late final _plc_tag_lock = _plc_tag_lockPtr.asFunction<int Function(int)>();

  int plc_tag_unlock(
    int tag,
  ) {
    return _plc_tag_unlock(
      tag,
    );
  }

  late final _plc_tag_unlockPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int32)>>(
          'plc_tag_unlock');
  late final _plc_tag_unlock =
      _plc_tag_unlockPtr.asFunction<int Function(int)>();

  int plc_tag_abort(
    int tag,
  ) {
    return _plc_tag_abort(
      tag,
    );
  }

  late final _plc_tag_abortPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int32)>>('plc_tag_abort');
  late final _plc_tag_abort = _plc_tag_abortPtr.asFunction<int Function(int)>();

  int plc_tag_destroy(
    int tag,
  ) {
    return _plc_tag_destroy(
      tag,
    );
  }

  late final _plc_tag_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int32)>>(
          'plc_tag_destroy');
  late final _plc_tag_destroy =
      _plc_tag_destroyPtr.asFunction<int Function(int)>();

  int plc_tag_read(
    int tag,
    int timeout,
  ) {
    return _plc_tag_read(
      tag,
      timeout,
    );
  }

  late final _plc_tag_readPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int32, ffi.Int)>>(
          'plc_tag_read');
  late final _plc_tag_read =
      _plc_tag_readPtr.asFunction<int Function(int, int)>();

  int plc_tag_status(
    int tag,
  ) {
    return _plc_tag_status(
      tag,
    );
  }

  late final _plc_tag_statusPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int32)>>(
          'plc_tag_status');
  late final _plc_tag_status =
      _plc_tag_statusPtr.asFunction<int Function(int)>();

  int plc_tag_write(
    int tag,
    int timeout,
  ) {
    return _plc_tag_write(
      tag,
      timeout,
    );
  }

  late final _plc_tag_writePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int32, ffi.Int)>>(
          'plc_tag_write');
  late final _plc_tag_write =
      _plc_tag_writePtr.asFunction<int Function(int, int)>();

  int plc_tag_get_int_attribute(
    int tag,
    ffi.Pointer<ffi.Char> attrib_name,
    int default_value,
  ) {
    return _plc_tag_get_int_attribute(
      tag,
      attrib_name,
      default_value,
    );
  }

  late final _plc_tag_get_int_attributePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Int32, ffi.Pointer<ffi.Char>,
              ffi.Int)>>('plc_tag_get_int_attribute');
  late final _plc_tag_get_int_attribute = _plc_tag_get_int_attributePtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Char>, int)>();

  int plc_tag_set_int_attribute(
    int tag,
    ffi.Pointer<ffi.Char> attrib_name,
    int new_value,
  ) {
    return _plc_tag_set_int_attribute(
      tag,
      attrib_name,
      new_value,
    );
  }

  late final _plc_tag_set_int_attributePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Int32, ffi.Pointer<ffi.Char>,
              ffi.Int)>>('plc_tag_set_int_attribute');
  late final _plc_tag_set_int_attribute = _plc_tag_set_int_attributePtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Char>, int)>();

  int plc_tag_get_byte_array_attribute(
    int tag,
    ffi.Pointer<ffi.Char> attrib_name,
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _plc_tag_get_byte_array_attribute(
      tag,
      attrib_name,
      buffer,
      buffer_length,
    );
  }

  late final _plc_tag_get_byte_array_attributePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Int32,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Int)>>('plc_tag_get_byte_array_attribute');
  late final _plc_tag_get_byte_array_attribute =
      _plc_tag_get_byte_array_attributePtr.asFunction<
          int Function(
              int, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Uint8>, int)>();

  int plc_tag_get_size(
    int tag,
  ) {
    return _plc_tag_get_size(
      tag,
    );
  }

  late final _plc_tag_get_sizePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int32)>>(
          'plc_tag_get_size');
  late final _plc_tag_get_size =
      _plc_tag_get_sizePtr.asFunction<int Function(int)>();

  int plc_tag_set_size(
    int tag,
    int new_size,
  ) {
    return _plc_tag_set_size(
      tag,
      new_size,
    );
  }

  late final _plc_tag_set_sizePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int32, ffi.Int)>>(
          'plc_tag_set_size');
  late final _plc_tag_set_size =
      _plc_tag_set_sizePtr.asFunction<int Function(int, int)>();

  int plc_tag_get_bit(
    int tag,
    int offset_bit,
  ) {
    return _plc_tag_get_bit(
      tag,
      offset_bit,
    );
  }

  late final _plc_tag_get_bitPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int32, ffi.Int)>>(
          'plc_tag_get_bit');
  late final _plc_tag_get_bit =
      _plc_tag_get_bitPtr.asFunction<int Function(int, int)>();

  int plc_tag_set_bit(
    int tag,
    int offset_bit,
    int val,
  ) {
    return _plc_tag_set_bit(
      tag,
      offset_bit,
      val,
    );
  }

  late final _plc_tag_set_bitPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Int32, ffi.Int, ffi.Int)>>(
      'plc_tag_set_bit');
  late final _plc_tag_set_bit =
      _plc_tag_set_bitPtr.asFunction<int Function(int, int, int)>();

  int plc_tag_get_uint64(
    int tag,
    int offset,
  ) {
    return _plc_tag_get_uint64(
      tag,
      offset,
    );
  }

  late final _plc_tag_get_uint64Ptr =
      _lookup<ffi.NativeFunction<ffi.Uint64 Function(ffi.Int32, ffi.Int)>>(
          'plc_tag_get_uint64');
  late final _plc_tag_get_uint64 =
      _plc_tag_get_uint64Ptr.asFunction<int Function(int, int)>();

  int plc_tag_set_uint64(
    int tag,
    int offset,
    int val,
  ) {
    return _plc_tag_set_uint64(
      tag,
      offset,
      val,
    );
  }

  late final _plc_tag_set_uint64Ptr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Int32, ffi.Int, ffi.Uint64)>>(
      'plc_tag_set_uint64');
  late final _plc_tag_set_uint64 =
      _plc_tag_set_uint64Ptr.asFunction<int Function(int, int, int)>();

  int plc_tag_get_int64(
    int tag,
    int offset,
  ) {
    return _plc_tag_get_int64(
      tag,
      offset,
    );
  }

  late final _plc_tag_get_int64Ptr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function(ffi.Int32, ffi.Int)>>(
          'plc_tag_get_int64');
  late final _plc_tag_get_int64 =
      _plc_tag_get_int64Ptr.asFunction<int Function(int, int)>();

  int plc_tag_set_int64(
    int arg0,
    int offset,
    int val,
  ) {
    return _plc_tag_set_int64(
      arg0,
      offset,
      val,
    );
  }

  late final _plc_tag_set_int64Ptr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Int32, ffi.Int, ffi.Int64)>>(
      'plc_tag_set_int64');
  late final _plc_tag_set_int64 =
      _plc_tag_set_int64Ptr.asFunction<int Function(int, int, int)>();

  int plc_tag_get_uint32(
    int tag,
    int offset,
  ) {
    return _plc_tag_get_uint32(
      tag,
      offset,
    );
  }

  late final _plc_tag_get_uint32Ptr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function(ffi.Int32, ffi.Int)>>(
          'plc_tag_get_uint32');
  late final _plc_tag_get_uint32 =
      _plc_tag_get_uint32Ptr.asFunction<int Function(int, int)>();

  int plc_tag_set_uint32(
    int tag,
    int offset,
    int val,
  ) {
    return _plc_tag_set_uint32(
      tag,
      offset,
      val,
    );
  }

  late final _plc_tag_set_uint32Ptr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Int32, ffi.Int, ffi.Uint32)>>(
      'plc_tag_set_uint32');
  late final _plc_tag_set_uint32 =
      _plc_tag_set_uint32Ptr.asFunction<int Function(int, int, int)>();

  int plc_tag_get_int32(
    int tag,
    int offset,
  ) {
    return _plc_tag_get_int32(
      tag,
      offset,
    );
  }

  late final _plc_tag_get_int32Ptr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int32, ffi.Int)>>(
          'plc_tag_get_int32');
  late final _plc_tag_get_int32 =
      _plc_tag_get_int32Ptr.asFunction<int Function(int, int)>();

  int plc_tag_set_int32(
    int arg0,
    int offset,
    int val,
  ) {
    return _plc_tag_set_int32(
      arg0,
      offset,
      val,
    );
  }

  late final _plc_tag_set_int32Ptr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Int32, ffi.Int, ffi.Int32)>>(
      'plc_tag_set_int32');
  late final _plc_tag_set_int32 =
      _plc_tag_set_int32Ptr.asFunction<int Function(int, int, int)>();

  int plc_tag_get_uint16(
    int tag,
    int offset,
  ) {
    return _plc_tag_get_uint16(
      tag,
      offset,
    );
  }

  late final _plc_tag_get_uint16Ptr =
      _lookup<ffi.NativeFunction<ffi.Uint16 Function(ffi.Int32, ffi.Int)>>(
          'plc_tag_get_uint16');
  late final _plc_tag_get_uint16 =
      _plc_tag_get_uint16Ptr.asFunction<int Function(int, int)>();

  int plc_tag_set_uint16(
    int tag,
    int offset,
    int val,
  ) {
    return _plc_tag_set_uint16(
      tag,
      offset,
      val,
    );
  }

  late final _plc_tag_set_uint16Ptr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Int32, ffi.Int, ffi.Uint16)>>(
      'plc_tag_set_uint16');
  late final _plc_tag_set_uint16 =
      _plc_tag_set_uint16Ptr.asFunction<int Function(int, int, int)>();

  int plc_tag_get_int16(
    int tag,
    int offset,
  ) {
    return _plc_tag_get_int16(
      tag,
      offset,
    );
  }

  late final _plc_tag_get_int16Ptr =
      _lookup<ffi.NativeFunction<ffi.Int16 Function(ffi.Int32, ffi.Int)>>(
          'plc_tag_get_int16');
  late final _plc_tag_get_int16 =
      _plc_tag_get_int16Ptr.asFunction<int Function(int, int)>();

  int plc_tag_set_int16(
    int arg0,
    int offset,
    int val,
  ) {
    return _plc_tag_set_int16(
      arg0,
      offset,
      val,
    );
  }

  late final _plc_tag_set_int16Ptr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Int32, ffi.Int, ffi.Int16)>>(
      'plc_tag_set_int16');
  late final _plc_tag_set_int16 =
      _plc_tag_set_int16Ptr.asFunction<int Function(int, int, int)>();

  int plc_tag_get_uint8(
    int tag,
    int offset,
  ) {
    return _plc_tag_get_uint8(
      tag,
      offset,
    );
  }

  late final _plc_tag_get_uint8Ptr =
      _lookup<ffi.NativeFunction<ffi.Uint8 Function(ffi.Int32, ffi.Int)>>(
          'plc_tag_get_uint8');
  late final _plc_tag_get_uint8 =
      _plc_tag_get_uint8Ptr.asFunction<int Function(int, int)>();

  int plc_tag_set_uint8(
    int tag,
    int offset,
    int val,
  ) {
    return _plc_tag_set_uint8(
      tag,
      offset,
      val,
    );
  }

  late final _plc_tag_set_uint8Ptr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Int32, ffi.Int, ffi.Uint8)>>(
      'plc_tag_set_uint8');
  late final _plc_tag_set_uint8 =
      _plc_tag_set_uint8Ptr.asFunction<int Function(int, int, int)>();

  int plc_tag_get_int8(
    int tag,
    int offset,
  ) {
    return _plc_tag_get_int8(
      tag,
      offset,
    );
  }

  late final _plc_tag_get_int8Ptr =
      _lookup<ffi.NativeFunction<ffi.Int8 Function(ffi.Int32, ffi.Int)>>(
          'plc_tag_get_int8');
  late final _plc_tag_get_int8 =
      _plc_tag_get_int8Ptr.asFunction<int Function(int, int)>();

  int plc_tag_set_int8(
    int arg0,
    int offset,
    int val,
  ) {
    return _plc_tag_set_int8(
      arg0,
      offset,
      val,
    );
  }

  late final _plc_tag_set_int8Ptr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Int32, ffi.Int, ffi.Int8)>>(
      'plc_tag_set_int8');
  late final _plc_tag_set_int8 =
      _plc_tag_set_int8Ptr.asFunction<int Function(int, int, int)>();

  double plc_tag_get_float64(
    int tag,
    int offset,
  ) {
    return _plc_tag_get_float64(
      tag,
      offset,
    );
  }

  late final _plc_tag_get_float64Ptr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Int32, ffi.Int)>>(
          'plc_tag_get_float64');
  late final _plc_tag_get_float64 =
      _plc_tag_get_float64Ptr.asFunction<double Function(int, int)>();

  int plc_tag_set_float64(
    int tag,
    int offset,
    double val,
  ) {
    return _plc_tag_set_float64(
      tag,
      offset,
      val,
    );
  }

  late final _plc_tag_set_float64Ptr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Int32, ffi.Int, ffi.Double)>>(
      'plc_tag_set_float64');
  late final _plc_tag_set_float64 =
      _plc_tag_set_float64Ptr.asFunction<int Function(int, int, double)>();

  double plc_tag_get_float32(
    int tag,
    int offset,
  ) {
    return _plc_tag_get_float32(
      tag,
      offset,
    );
  }

  late final _plc_tag_get_float32Ptr =
      _lookup<ffi.NativeFunction<ffi.Float Function(ffi.Int32, ffi.Int)>>(
          'plc_tag_get_float32');
  late final _plc_tag_get_float32 =
      _plc_tag_get_float32Ptr.asFunction<double Function(int, int)>();

  int plc_tag_set_float32(
    int tag,
    int offset,
    double val,
  ) {
    return _plc_tag_set_float32(
      tag,
      offset,
      val,
    );
  }

  late final _plc_tag_set_float32Ptr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Int32, ffi.Int, ffi.Float)>>(
      'plc_tag_set_float32');
  late final _plc_tag_set_float32 =
      _plc_tag_set_float32Ptr.asFunction<int Function(int, int, double)>();

  int plc_tag_set_raw_bytes(
    int id,
    int offset,
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _plc_tag_set_raw_bytes(
      id,
      offset,
      buffer,
      buffer_length,
    );
  }

  late final _plc_tag_set_raw_bytesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Int32, ffi.Int, ffi.Pointer<ffi.Uint8>,
              ffi.Int)>>('plc_tag_set_raw_bytes');
  late final _plc_tag_set_raw_bytes = _plc_tag_set_raw_bytesPtr
      .asFunction<int Function(int, int, ffi.Pointer<ffi.Uint8>, int)>();

  int plc_tag_get_raw_bytes(
    int id,
    int offset,
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _plc_tag_get_raw_bytes(
      id,
      offset,
      buffer,
      buffer_length,
    );
  }

  late final _plc_tag_get_raw_bytesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Int32, ffi.Int, ffi.Pointer<ffi.Uint8>,
              ffi.Int)>>('plc_tag_get_raw_bytes');
  late final _plc_tag_get_raw_bytes = _plc_tag_get_raw_bytesPtr
      .asFunction<int Function(int, int, ffi.Pointer<ffi.Uint8>, int)>();

  int plc_tag_get_string(
    int tag_id,
    int string_start_offset,
    ffi.Pointer<ffi.Char> buffer,
    int buffer_length,
  ) {
    return _plc_tag_get_string(
      tag_id,
      string_start_offset,
      buffer,
      buffer_length,
    );
  }

  late final _plc_tag_get_stringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Int32, ffi.Int, ffi.Pointer<ffi.Char>,
              ffi.Int)>>('plc_tag_get_string');
  late final _plc_tag_get_string = _plc_tag_get_stringPtr
      .asFunction<int Function(int, int, ffi.Pointer<ffi.Char>, int)>();

  int plc_tag_set_string(
    int tag_id,
    int string_start_offset,
    ffi.Pointer<ffi.Char> string_val,
  ) {
    return _plc_tag_set_string(
      tag_id,
      string_start_offset,
      string_val,
    );
  }

  late final _plc_tag_set_stringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Int32, ffi.Int,
              ffi.Pointer<ffi.Char>)>>('plc_tag_set_string');
  late final _plc_tag_set_string = _plc_tag_set_stringPtr
      .asFunction<int Function(int, int, ffi.Pointer<ffi.Char>)>();

  int plc_tag_get_string_length(
    int tag_id,
    int string_start_offset,
  ) {
    return _plc_tag_get_string_length(
      tag_id,
      string_start_offset,
    );
  }

  late final _plc_tag_get_string_lengthPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int32, ffi.Int)>>(
          'plc_tag_get_string_length');
  late final _plc_tag_get_string_length =
      _plc_tag_get_string_lengthPtr.asFunction<int Function(int, int)>();

  int plc_tag_get_string_capacity(
    int tag_id,
    int string_start_offset,
  ) {
    return _plc_tag_get_string_capacity(
      tag_id,
      string_start_offset,
    );
  }

  late final _plc_tag_get_string_capacityPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int32, ffi.Int)>>(
          'plc_tag_get_string_capacity');
  late final _plc_tag_get_string_capacity =
      _plc_tag_get_string_capacityPtr.asFunction<int Function(int, int)>();

  int plc_tag_get_string_total_length(
    int tag_id,
    int string_start_offset,
  ) {
    return _plc_tag_get_string_total_length(
      tag_id,
      string_start_offset,
    );
  }

  late final _plc_tag_get_string_total_lengthPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int32, ffi.Int)>>(
          'plc_tag_get_string_total_length');
  late final _plc_tag_get_string_total_length =
      _plc_tag_get_string_total_lengthPtr.asFunction<int Function(int, int)>();
}

abstract class plctag_error_code_t {
  static const int PLCTAG_STATUS_PENDING = 1;
  static const int PLCTAG_STATUS_OK = 0;
  static const int PLCTAG_ERR_ABORT = -1;
  static const int PLCTAG_ERR_BAD_CONFIG = -2;
  static const int PLCTAG_ERR_BAD_CONNECTION = -3;
  static const int PLCTAG_ERR_BAD_DATA = -4;
  static const int PLCTAG_ERR_BAD_DEVICE = -5;
  static const int PLCTAG_ERR_BAD_GATEWAY = -6;
  static const int PLCTAG_ERR_BAD_PARAM = -7;
  static const int PLCTAG_ERR_BAD_REPLY = -8;
  static const int PLCTAG_ERR_BAD_STATUS = -9;
  static const int PLCTAG_ERR_CLOSE = -10;
  static const int PLCTAG_ERR_CREATE = -11;
  static const int PLCTAG_ERR_DUPLICATE = -12;
  static const int PLCTAG_ERR_ENCODE = -13;
  static const int PLCTAG_ERR_MUTEX_DESTROY = -14;
  static const int PLCTAG_ERR_MUTEX_INIT = -15;
  static const int PLCTAG_ERR_MUTEX_LOCK = -16;
  static const int PLCTAG_ERR_MUTEX_UNLOCK = -17;
  static const int PLCTAG_ERR_NOT_ALLOWED = -18;
  static const int PLCTAG_ERR_NOT_FOUND = -19;
  static const int PLCTAG_ERR_NOT_IMPLEMENTED = -20;
  static const int PLCTAG_ERR_NO_DATA = -21;
  static const int PLCTAG_ERR_NO_MATCH = -22;
  static const int PLCTAG_ERR_NO_MEM = -23;
  static const int PLCTAG_ERR_NO_RESOURCES = -24;
  static const int PLCTAG_ERR_NULL_PTR = -25;
  static const int PLCTAG_ERR_OPEN = -26;
  static const int PLCTAG_ERR_OUT_OF_BOUNDS = -27;
  static const int PLCTAG_ERR_READ = -28;
  static const int PLCTAG_ERR_REMOTE_ERR = -29;
  static const int PLCTAG_ERR_THREAD_CREATE = -30;
  static const int PLCTAG_ERR_THREAD_JOIN = -31;
  static const int PLCTAG_ERR_TIMEOUT = -32;
  static const int PLCTAG_ERR_TOO_LARGE = -33;
  static const int PLCTAG_ERR_TOO_SMALL = -34;
  static const int PLCTAG_ERR_UNSUPPORTED = -35;
  static const int PLCTAG_ERR_WINSOCK = -36;
  static const int PLCTAG_ERR_WRITE = -37;
  static const int PLCTAG_ERR_PARTIAL = -38;
  static const int PLCTAG_ERR_BUSY = -39;
}

/// Debug level constants - generated from debug_levels.def
abstract class plctag_debug_level_t {
  static const int PLCTAG_DEBUG_NONE = 0;
  static const int PLCTAG_DEBUG_ERROR = 1;
  static const int PLCTAG_DEBUG_WARN = 2;
  static const int PLCTAG_DEBUG_INFO = 3;
  static const int PLCTAG_DEBUG_DETAIL = 4;
  static const int PLCTAG_DEBUG_SPEW = 5;
}

/// @brief Debug Module Definitions.
///
/// The following module IDs can be used with the module-specific debug functions.
/// Each module represents a different subsystem within libplctag and can have its
/// own independent debug level setting.
///
/// This is the canonical list of module IDs used throughout the library.
///
/// @note Do not rely on these values remaining constant between library versions
/// as they will likely be added to in future releases.
abstract class plctag_debug_module_t {
  static const int PLCTAG_MODULE_LIB = 0;
  static const int PLCTAG_MODULE_INIT = 1;
  static const int PLCTAG_MODULE_VERSION = 2;
  static const int PLCTAG_MODULE_UTILS = 3;
  static const int PLCTAG_MODULE_AB_SESSION = 4;
  static const int PLCTAG_MODULE_AB_PCCC = 5;
  static const int PLCTAG_MODULE_AB_CIP = 6;
  static const int PLCTAG_MODULE_AB_COMMON = 7;
  static const int PLCTAG_MODULE_AB_EIP_CIP = 8;
  static const int PLCTAG_MODULE_AB_EIP_CIP_SPECIAL = 9;
  static const int PLCTAG_MODULE_AB_EIP_LGX_PCCC = 10;
  static const int PLCTAG_MODULE_AB_EIP_PLC5_PCCC = 11;
  static const int PLCTAG_MODULE_AB_EIP_PLC5_DHP = 12;
  static const int PLCTAG_MODULE_AB_EIP_SLC_PCCC = 13;
  static const int PLCTAG_MODULE_AB_EIP_SLC_DHP = 14;
  static const int PLCTAG_MODULE_AB_ERROR = 15;
  static const int PLCTAG_MODULE_OMRON_CONN = 16;
  static const int PLCTAG_MODULE_OMRON_CIP = 17;
  static const int PLCTAG_MODULE_OMRON_COMMON = 18;
  static const int PLCTAG_MODULE_OMRON_STANDARD_TAG = 19;
  static const int PLCTAG_MODULE_OMRON_RAW_TAG = 20;
  static const int PLCTAG_MODULE_MODBUS = 21;
  static const int PLCTAG_MODULE_SYSTEM = 22;
  static const int PLCTAG_MODULE_PLATFORM = 23;
  static const int PLCTAG_MODULE_AB_CONNECTION = 24;
  static const int PLCTAG_MODULE_MB_CONNECTION = 25;
  static const int PLCTAG_MODULE_OMRON_CONNECTION = 26;
}

/// @brief Tag event type enumeration.
///
/// Event types that trigger tag callbacks:
/// - PLCTAG_EVENT_READ_STARTED: Tag read operation has started.
/// - PLCTAG_EVENT_READ_COMPLETED: Tag read operation has completed.
/// - PLCTAG_EVENT_WRITE_STARTED: Tag write operation has started.
/// - PLCTAG_EVENT_WRITE_COMPLETED: Tag write operation has completed.
/// - PLCTAG_EVENT_ABORTED: Tag operation has been aborted.
/// - PLCTAG_EVENT_DESTROYED: Tag is being destroyed.
/// - PLCTAG_EVENT_CREATED: Tag has been created.
abstract class plctag_event_t {
  static const int PLCTAG_EVENT_READ_STARTED = 1;
  static const int PLCTAG_EVENT_READ_COMPLETED = 2;
  static const int PLCTAG_EVENT_WRITE_STARTED = 3;
  static const int PLCTAG_EVENT_WRITE_COMPLETED = 4;
  static const int PLCTAG_EVENT_ABORTED = 5;
  static const int PLCTAG_EVENT_DESTROYED = 6;
  static const int PLCTAG_EVENT_CREATED = 7;
  static const int PLCTAG_EVENT_CONN_STATUS_OFFSET = 100;
  static const int PLCTAG_EVENT_CONN_STATUS_UP = 100;
  static const int PLCTAG_EVENT_CONN_STATUS_DOWN = 101;
  static const int PLCTAG_EVENT_CONN_STATUS_DISCONNECTING = 102;
  static const int PLCTAG_EVENT_CONN_STATUS_CONNECTING = 103;
  static const int PLCTAG_EVENT_CONN_STATUS_IDLE_WAIT = 104;
  static const int PLCTAG_EVENT_CONN_STATUS_ERR_WAIT = 105;
  static const int PLCTAG_EVENT_MAX = 105;
}
