name: libplctag-dart-example # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Example of the libplctag_dart library # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
 - build-on: arm64
   run-on: arm64
   
plugs:
  graphics-core20:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core20

apps:
  libplctag-dart-example:
#    command-chain:
#     - bin/wayland-launch
    command: example
    plugs:
     - wayland
     - opengl
     - network

  daemon:
    daemon: simple
    restart-condition: always
    command-chain:
    - bin/run-daemon
    - bin/wayland-launch
    command: "example --fullscreen"

parts:
  example:
    plugin: dump
    source: ./build/elinux/arm64/release/bundle
    stage-packages:
       - "libegl1"
       - "libx11-6"
       - "libxkbcommon0"
       - "libwayland-cursor0"
       - "libwayland-egl1"
       - "libstdc++6"
       - inotify-tools
  libplctag:
    plugin: dump
    source: ./elinux/libplctag
  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl wayland graphics-core20
    stage-packages:
      - inotify-tools
   
    
environment:
  # Graphics from graphics-core20
  LD_LIBRARY_PATH:    $SNAP/graphics/lib
  LIBGL_DRIVERS_PATH: $SNAP/graphics/dri
  LIBVA_DRIVERS_PATH: $SNAP/graphics/dri
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/graphics/glvnd/egl_vendor.d
  # XKB config from snap
  XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb

layout:
  /usr/share/libdrm:  # Needed by mesa-core20 on AMD GPUs
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:  # Used by mesa-core20 for app specific workarounds
    bind: $SNAP/graphics/drirc.d
